CREATE DATABASE IF NOT EXISTS rampout_db;
USE rampout_db;

CREATE TABLE host (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(9) NOT NULL unique,
  password VARCHAR(256) NOT NULL,
  Creado DATETIME DEFAULT CURRENT_TIMESTAMP,
  Modificado DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

